import { LandingGame, SponsorTier } from "./landing.models";

export const LANDING_GAMES: LandingGame[] = [
  {
    name: "Calcio a 5",
    description: "Squadre, gironi e partite ad alta intensità.",
    details: "Il classico torneo di quartiere, ritmo alto e grande tifo.",
    image: "/assets/icone/icona-calcio.svg",
    format: "A squadre",
    audience: "Open",
    highlights: [
      "Partite veloci e calendario concentrato.",
      "Gironi iniziali e fase a eliminazione.",
      "Premiazione finale.",
    ],
    rules: [
      "Squadre composte da massimo 8 giocatori.",
      "Formula con gironi iniziali e fase a eliminazione diretta. In caso di pareggio nelle fasi finali si procede ai rigori.",
      "In caso di parità in classifica valgono, nell'ordine: scontri diretti, differenza reti, gol fatti e sorteggio.",
      "Si applicano le regole ufficiali del calcio a 5.",
      "Ritardo massimo consentito: 10 minuti. Oltre il limite, sconfitta 6-0 a tavolino.",
      "Rispetto obbligatorio per arbitri, avversari e organizzazione. Bestemmie, risse o comportamenti antisportivi possono portare ad ammonizione, espulsione o esclusione.",
      "Quota: 80 euro per squadra, più 10 euro a partita per squadra.",
      "Iscrizioni aperte fino al 19 giugno.",
      "I capitani saranno inseriti in un gruppo WhatsApp dedicato con regolamento ufficiale e comunicazioni organizzative.",
    ],
  },
  {
    name: "Calcio a 5 under 15",
    description:
      "Il torneo dedicato ai piu giovani con gironi, fase finale e regole pensate per categoria e sicurezza.",
    details:
      "Torneo a squadre per giocatori con 16 anni non compiuti, con quota iscrizione da 40 euro e quota partita da 5 euro per squadra.",
    image: "/assets/icone/icona-calcio.svg",
    format: "A squadre",
    audience: "Under 15",
    highlights: [
      "Squadre composte da massimo 8 giocatori, con 5 giocatori in campo.",
      "Possono partecipare solo giocatori con 16 anni non compiuti.",
      "Formula con gironi piu eliminazione diretta.",
      "Quota iscrizione: 40 euro a squadra.",
      "Quota partita: 5 euro a partita per squadra.",
      "Gruppo WhatsApp dedicato ai capitani con regolamento ufficiale e comunicazioni.",
    ],
    rules: [
      "Squadre composte da massimo 8 giocatori. In campo giocano 5 giocatori.",
      "Possono partecipare solo giocatori con 16 anni non compiuti.",
      "Formula con gironi piu eliminazione diretta. In caso di pareggio nelle fasi finali si procede ai rigori.",
      "In caso di parita in classifica valgono, nell'ordine: scontri diretti, differenza reti, gol fatti e sorteggio.",
      "Si applicano le regole ufficiali del calcio a 5.",
      "Ritardo massimo consentito: 10 minuti. Oltre il limite, sconfitta 6-0 a tavolino.",
      "Rispetto obbligatorio per arbitri, avversari e organizzazione. Bestemmie, risse o comportamenti antisportivi possono portare ad ammonizione, espulsione o esclusione dal torneo.",
      "Quota iscrizione: 40 euro a squadra. Quota partita: 5 euro a partita per squadra.",
      "Per i capitani verrà creato un gruppo WhatsApp con regolamento ufficiale e comunicazioni del torneo.",
      "Essendo un torneo per minorenni, per ogni giocatore sara necessaria un'autorizzazione firmata da un genitore o tutore.",
      "Info e iscrizioni in DM, su lafossagames.com o al 366 4202641, Walter.",
    ],
  },
  {
    name: "Green Volley",
    description: "Torneo 3 vs 3 su campo in erba sintetica.",
    image: "/assets/icone/icona-pallavolo.svg",
    details:
      "Area Mercato, Santa Maria la Fossa. Iscrizioni aperte fino al 19 giugno.",
    format: "3 vs 3",
    audience: "Open",
    highlights: [
      "Squadre da 3 giocatori, con massimo 5 giocatori in rosa.",
      "Massimo 1 tesserato FIPAV per squadra.",
      "Quota iscrizione: 50 euro a squadra.",
      "Campo in erba sintetica.",
      "I capitani saranno aggiunti a un gruppo WhatsApp con regolamento ufficiale e comunicazioni.",
    ],
    rules: [
      "Formula con gironi più fase a eliminazione diretta.",
      "Partite al meglio dei 3 set: primi due set ai 21 punti, eventuale terzo set ai 15.",
      "Classifica gironi: vittoria 3 punti, sconfitta 0 punti.",
      "In caso di parità valgono, nell'ordine: scontri diretti, differenza set, differenza punti e sorteggio.",
      "Si applicano le regole ufficiali del green volley.",
      "Cambi illimitati, battuta libera anche dall'alto e rotazione obbligatoria.",
      "Punto per l'avversario in caso di tocco di rete, tocco della linea in battuta o più di 3 tocchi escluso il muro.",
      "Ritardo massimo consentito: 10 minuti. Oltre il limite, partita persa a tavolino.",
      "Rispetto obbligatorio per arbitri, avversari e organizzazione. Bestemmie, risse o atti antisportivi possono portare ad ammonizione, espulsione o esclusione.",
      "Info e iscrizioni in DM o al 335 5653748, Gaetano.",
    ],
  },
  {
    name: "Calcio balilla",
    description:
      "Torneo a coppie con gironi all'italiana, fasi finali e regolamento tecnico dedicato.",
    image: "/assets/icone/icona-calcio-balilla.svg",
    details:
      "Sfide a coppie dove coordinazione, tecnica e rapidita fanno la differenza, con quota iscrizione da 20 euro e chiusura iscrizioni il 19 giugno.",
    format: "A coppie",
    audience: "Open",
    highlights: [
      "Formula con gironi all'italiana piu eliminazione diretta.",
      "Gironi su set unico a 11 punti.",
      "Fasi finali su 2 set a 7 con eventuale terzo set a 9.",
      "Quota iscrizione: 20 euro per squadra.",
      "Termine iscrizioni: 19 giugno.",
      "Gruppo WhatsApp dedicato ai capitani con regolamento ufficiale completo.",
    ],
    rules: [
      "Formula: gironi all'italiana piu eliminazione diretta con quarti e semifinali.",
      "Nei gironi si gioca un set a 11 punti. Sul 10-10 il set puo terminare in pareggio.",
      "Nelle fasi finali si giocano 2 set a 7 punti, con eventuale terzo set a 9 punti.",
      "In caso di parita nella classifica dei gironi valgono, nell'ordine: scontri diretti, differenza punti, maggior numero di punti fatti, minor numero di punti subiti e sorteggio.",
      "Sono consentiti tocchi illimitati tra omini della stessa zona.",
      "Il tiro e consentito in 1 tocco singolo per stecca, oppure in 2 o piu tocchi con sponda e o battente prima del tiro.",
      "Servizio dalla difesa: palla ferma posizionata in difesa, tocco con battente o sponda di fondo, chiamata stop e poi battente laterale.",
      "Per qualsiasi controversia, la decisione inappellabile spetta alla direzione del torneo.",
      "Il regolamento ufficiale completo verra inviato ai capitani tramite gruppo WhatsApp dedicato.",
      "Info e iscrizioni in DM, su lafossagames.com o al 334 3848067, Pierpaolo.",
    ],
  },
  {
    name: "Briscola",
    description:
      "Torneo a coppie con gironi, fasi finali e partite a 120 punti.",
    image: "/assets/icone/icona-briscola.svg",
    details:
      "Sfide al meglio delle partite, classifica a punti e regolamento dedicato per gestire spareggi e parità.",
    format: "A coppie",
    audience: "Open",
    highlights: [
      "Fase a gironi al meglio delle 3 partite.",
      "Fasi finali al meglio delle 5 partite.",
      "Quota iscrizione: 20 euro a squadra.",
      "Iscrizioni aperte fino al 19 giugno.",
      "Gruppo WhatsApp per capitani con regolamento ufficiale e comunicazioni.",
    ],
    rules: [
      "Fase a gironi: sfide al meglio delle 3 partite a 120 punti.",
      "In caso di 1-1 nei gironi si gioca uno spareggio secco a 120 punti.",
      "In caso di parità nel singolo scontro dei gironi, ad esempio 70-50 e 50-70, si gioca una minipartita a 60 punti.",
      "Ogni vittoria nella fase a gironi vale 3 punti.",
      "A parità di punti in classifica conta la differenza tra 120 vinti e 120 persi. Se la parità persiste, si gioca una partita di spareggio con le stesse modalità.",
      "Fasi finali: sfide al meglio delle 5 partite a 120 punti.",
      "In caso di 2-2 nelle fasi finali si gioca uno spareggio secco a 120 punti.",
      "In caso di parità nel singolo scontro delle fasi finali si gioca una nuova partita a 120 punti.",
      "Durante tutta la partita è consentito parlare con il proprio compagno.",
      "È vietato rivedere il mazzetto delle carte già giocate.",
      "Se un giocatore sbaglia a giocare una carta, la mano può essere ripetuta solo con il consenso degli avversari. La scelta vale per tutta la partita e si applica a entrambe le coppie.",
      "Ritardo massimo consentito: 15 minuti. Oltre il limite, partita persa a tavolino.",
      "Gironi, calendario, accoppiamenti e tabellone saranno comunicati prima dell'inizio del torneo.",
      "Info e iscrizioni in DM, su lafossagames.com o al 351 5578081, Gianmarco.",
    ],
  },
  {
    name: "FC 26",
    description:
      "Torneo singolo con gironi, fase finale e regole ufficiali condivise prima dell'inizio.",
    image: "/assets/icone/icona-fc26.svg",
    details:
      "Torneo eSports in presenza uno contro uno con quota di iscrizione da 10 euro e chiusura iscrizioni il 19 giugno.",
    format: "Singolo",
    audience: "Open",
    highlights: [
      "Iscrizione singola.",
      "Formula con gironi piu eliminazione diretta.",
      "Partite da 6 minuti per tempo con visuale tribuna stampa.",
      "Quota iscrizione: 10 euro.",
      "Iscrizioni aperte fino al 19 giugno.",
      "Gruppo WhatsApp dedicato con regolamento ufficiale e comunicazioni del torneo.",
    ],
    rules: [
      "Formula torneo: gironi piu eliminazione diretta.",
      "Le partite durano 6 minuti per tempo.",
      "La visuale di gioco sara tribuna stampa per tutte le partite del torneo.",
      "Squadre e impostazioni consentite saranno comunicate prima dell'inizio del torneo.",
      "In caso di parita nel girone valgono, nell'ordine: scontri diretti, differenza reti, gol fatti e sorteggio.",
      "Ritardo massimo consentito: 10 minuti. Oltre il limite, sconfitta a tavolino.",
      "Rispetto obbligatorio per avversari e organizzazione. Offese, comportamenti antisportivi o scorrettezze possono portare ad ammonizione o esclusione dal torneo.",
      "Verrà creato un gruppo WhatsApp con regolamento ufficiale e comunicazioni del torneo.",
      "Info e iscrizioni in DM, su lafossagames.com o al 334 3848067, Pierpaolo.",
    ],
  },
  {
    name: "Ping pong",
    description:
      "Torneo singolo con gironi, fase finale e regolamento dedicato per set, servizio e spareggi.",
    image: "/assets/icone/icona-pingpong.svg",
    details:
      "Velocita, tecnica e riflessi in un torneo individuale con quota di iscrizione da 10 euro e chiusura iscrizioni il 19 giugno.",
    format: "Singolo",
    audience: "Open",
    highlights: [
      "Formula con gironi piu eliminazione diretta.",
      "Gironi al meglio di 3 set a 15 punti.",
      "Fase finale al meglio di 3 set a 21 punti.",
      "Quota iscrizione: 10 euro.",
      "Iscrizioni aperte fino al 19 giugno.",
      "Gruppo WhatsApp dedicato con regolamento ufficiale e comunicazioni del torneo.",
    ],
    rules: [
      "Formula torneo: gironi piu eliminazione diretta.",
      "Fase a gironi: partite al meglio di 3 set a 15 punti con cambio battitore ogni somma di 3 punti.",
      "In caso di 14 pari nei gironi, il set si conclude con doppio vantaggio.",
      "Fase a eliminazione diretta: partite al meglio di 3 set a 21 punti con cambio battitore ogni somma di 5 punti.",
      "In caso di 20 pari nella fase a eliminazione diretta, il set si conclude con doppio vantaggio.",
      "In caso di parita nel girone valgono, nell'ordine: scontri diretti, differenza set, punti fatti e partita secca da 1 set a 15 punti.",
      "Ritardo massimo consentito: 10 minuti. Oltre il limite, sconfitta a tavolino.",
      "Rispetto obbligatorio per avversari e organizzazione. Comportamenti antisportivi, offese o discussioni eccessive possono portare ad ammonizione o esclusione dal torneo.",
      "Verrà creato un gruppo WhatsApp con regolamento ufficiale e comunicazioni del torneo.",
      "Info e iscrizioni in DM, su lafossagames.com o al 334 3848067, Pierpaolo.",
    ],
  },
];

export const SPONSOR_TIERS: SponsorTier[] = [
  {
    name: "Platino",
    color: "#e5e4e2",
    description:
      "La partnership premium per chi desidera la massima presenza online e durante l'evento.",
    perks: [
      "Tutti i vantaggi dei pacchetti precedenti",
      "Massima visibilità durante l'evento",
      "Banner di formato superiore",
      "Visibilità sulle magliette staff lato frontale",
      "Massima esposizione su social e sito web",
      "Ringraziamento finale con targhetta dedicata",
    ],
  },
  {
    name: "Oro",
    color: "#ffd400",
    description:
      "Il pacchetto avanzato per aumentare la presenza del brand sui canali ufficiali e negli spazi evento.",
    perks: [
      "Tutti i vantaggi del pacchetto Argento",
      "Maggiore visibilità all'interno del sito",
      "Logo sulla maglia staff lato retro in formato ridotto",
      "Gadget personalizzati",
      "Targhetta sul bancone insieme agli sponsor principali",
    ],
  },
  {
    name: "Argento",
    color: "#c8c8c8",
    description:
      "La soluzione intermedia con presenza dedicata su social, materiali fisici e touchpoint digitali.",
    perks: [
      "Post social singolo dedicato",
      "Storia Instagram singola",
      "Cartellone 1x1 dedicato",
      "Eventuale visibilità su monitor durante l'evento",
      "Banner dedicato sul sito",
      "Piccolo gadget",
    ],
  },
  {
    name: "Bronzo",
    color: "#d98945",
    description:
      "L'ingresso ideale per sostenere l'evento con una presenza concreta su social, sito e materiali condivisi.",
    perks: [
      "Storia Instagram collettiva",
      "Post social collettivo della fascia",
      "Banner 3x2 condiviso con gli sponsor della stessa fascia",
      "Mini spazio sul sito insieme agli sponsor della fascia",
      "Banner 1x1 condiviso con 4 sponsor",
    ],
  },
];
